name: SSH Session Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true

    - name: Echo test
      run: |
        echo "The SSH session is active. Check the workflow logs for the SSH command."
